### ISSUE TITLE
copyleft?

### ISSUE THREAD

**Issue by Be-ing** [jcelerier/libremidi#35]
Considering this is a fork/combination of two other libraries with lax permissive licenses, I am wondering if you have considered changing the license to a copyleft license. I'd encourage the Mozilla Public License 2.0 if you want this to be used in proprietary software, otherwise the GPL would be a good choice IMO.

**Comment by Be-ing** [comment]
https://www.youtube.com/watch?v=zxIEDNyZOkA#t=20m32s

**Comment by jcelerier** [comment]
While I tend to license my own work under AGPLv3, here most of the code comes from rtmidi and modernmidi - I'd be inclined to continue respecting the original author's wishes regarding licensing for these libraries.

**Comment by atsushieno** [comment]
Regardless of your intent, lack of declared licensing information on *your own changes* remain "not licensed at all"...

**Comment by Be-ing** [comment]
It is not immediately obvious which code came from RtMidi versus ModernMidi. Or is it so mixed together that it's hard to tell anymore?

**Comment by atsushieno** [comment]
There are at least things like WebMIDI support that does not exist in either of the origins.

**Comment by jcelerier** [comment]
Good point @atsushieno.

What would you think of LGPLv3 as a compromise for contributions to this repo ? (The main lib i'm using libremidi for is LGPLv3 and must stay that way due to a situation I don't have control over)

Regarding what comes from where, realtime I/O is from rtmidi, file I/O is from modernmidi.

**Comment by atsushieno** [comment]
You have no reason to hesitate to choose LGPLv3 or whatever that do not contradict the origins. Yet, you don't have to choose LGPLv3 for libremidi to use it in your LGPLv3 projects. It can stay BSD-like. Only GPL family would expand free software world though.

I may avoid it depending on how my own projects would go (for example if I plan to use it for iOS, then I will have to cancel using it as LGPL is incompatible with App Store), but it is totally up to your will and I support your decision :-)

**Comment by jcelerier** [comment]
> LGPL is incompatible with App Store

it's not been the case for half a decade, see for instance the "iOS" section here: https://github.com/freedesktop/gstreamer/blob/master/README.static-linking (and the list of LGPL or even GPL apps there: https://en.wikipedia.org/wiki/List_of_free_and_open-source_iOS_applications)

**Comment by atsushieno** [comment]
In theory, it's not only Apple but also those authors of the GPLed code that can ban those apps. The apps can be listed there because those authors didn't complain. It is a matter of licensed user (for example, me), not the licenser (you), who would be worry about sudden possible prohibition in the future :-)

If you don't claim any copyright for App Store incompatibility, it would be good to add exception statement within the license. At this state you are (most likely) the only one who has right for that, so unlike old projects [like Fluidsynth](https://github.com/FluidSynth/fluidsynth/wiki/LicensingFAQ#ios-and-the-app-store) an exception would totally suffice.

**Comment by atsushieno** [comment]
Sorry for spamming, I should have mentioned a side effect of adding App Store exception - with GPL/LGPL you could sell commercial licenses to those who sell apps at App Store, but the exception term would simply disable the scheme. I used to work at such a company who sold commercial license for their iOS app runtime.

**Comment by Be-ing** [comment]
I would not recommend LGPL if your intention is for this library to actually be used by and receive contributions from developers of proprietary applications. The relinking requirements of the LGPL are weird and generally impractical to satisfy for proprietary software. (I personally also think they have little practical impact on users' freedom, but they do keep proprietary software developers away.) The Mozilla Public License is IMO a better fit if you want the library to be usable in proprietary software. The library remains copyleft so if it is incorporated in proprietary software, any modifications made to it need to have source code published.

**Comment by jcelerier** [comment]
Hm, I looked at this which seems to explain the difference : https://softwareengineering.stackexchange.com/questions/221365/mozilla-public-license-mpl-2-0-vs-lesser-gnu-general-public-license-lgpl-3-0

but it is wrong - LGPL does not prevent static linking, from the horse's mouth: https://www.gnu.org/licenses/gpl-faq.en.html#LGPLStaticVsDynamic

- MPL does not have a "You may not impose any further restrictions on the exercise of the rights granted or affirmed under this License." clause, which is something I'd like to uphold

- I'm not really a fan of file-based licences, which require license headers, when we have git blame available .

- Qt, WebKit and FFMPEG are all LGPL and neither seem to cause problems for being embedded in proprietary apps such as Chrome, Max/MSP, etc. 

Let's have a poll:

* [option A] LGPLv3 if we want to uphold the ability for end-users to access libremidi's source if it ends up being used, modified or not, in a proprietary app or hardware device (in particular, I'd rather not have $MANUFACTURER put / modify this code in a hardware synth without giving it back)
* [option B] Go full permissive with https://spdx.org/licenses/MIT.html license and rely on the goodwill of developers that may use it to backport improvements
* [option C] AGPLv3 (my heart goes to this but sadly I would then be unable to use it in the main software I work on)
* [option D] MPLv2

[option A] has my preference so I'll cast a vote for it, please vote (and add options as you see fit)

**Comment by atsushieno** [comment]
B is most versatile for me as I can embed the compiled binaries in my MIT licensed libraries and apps, but such projects don't exist yet so my choice is not very responsible.

**Comment by jcelerier** [comment]
> Regardless of your intent, lack of declared licensing information on _your own changes_ remain "not licensed at all"...

Regarding that I read the github terms of service yesterday and they actually mention that if nothing is explicitely said in the new changes, they are assumed licensed under the same terms than the existing code so that part is at least not an issue.

So, to keep things simple let's leave it at that for the time being : contributions to {reader,writer}.{hpp,cpp} are under the modernmidi license, contributions to all the other files are under the rtmidi license.
